Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/configpile-OmRJEK4a-py3.8/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/configpile-OmRJEK4a-py3.8/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.cache/pypoetry/virtualenvs/configpile-OmRJEK4a-py3.8/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/.cache/pypoetry/virtualenvs/configpile-OmRJEK4a-py3.8/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/runner/.cache/pypoetry/virtualenvs/configpile-OmRJEK4a-py3.8/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/configpile-OmRJEK4a-py3.8/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/configpile-OmRJEK4a-py3.8/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from configpile import *

class FloatParser(Parser[float]):
    def parse(self, arg: str) -> Res[float]:
        try:
            return float(arg)
        except ValueError as e:
            return Err.make(str(e))

fp = FloatParser()

------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 1>[0;34m()[0m
[0;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mconfigpile[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m      3[0m [38;5;28;01mclass[39;00m [38;5;21;01mFloatParser[39;00m(Parser[[38;5;28mfloat[39m]):
[1;32m      4[0m     [38;5;28;01mdef[39;00m [38;5;21mparse[39m([38;5;28mself[39m, arg: [38;5;28mstr[39m) [38;5;241m-[39m[38;5;241m>[39m Res[[38;5;28mfloat[39m]:

[0;31mAttributeError[0m: module 'configpile' has no attribute 'fun'
AttributeError: module 'configpile' has no attribute 'fun'

