Traceback (most recent call last):
  File "/home/runner/.cache/pypoetry/virtualenvs/configpile-OmRJEK4a-py3.8/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/.cache/pypoetry/virtualenvs/configpile-OmRJEK4a-py3.8/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/runner/.cache/pypoetry/virtualenvs/configpile-OmRJEK4a-py3.8/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/runner/.cache/pypoetry/virtualenvs/configpile-OmRJEK4a-py3.8/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/runner/.cache/pypoetry/virtualenvs/configpile-OmRJEK4a-py3.8/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/.cache/pypoetry/virtualenvs/configpile-OmRJEK4a-py3.8/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/.cache/pypoetry/virtualenvs/configpile-OmRJEK4a-py3.8/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from dataclasses import dataclass
from configpile import *
from typing_extensions import Annotated
from typing import Optional


def int_is_not_negative(x: int) -> bool:
    return x >= 0

@dataclass(frozen=True)
class TestConfig(Config):

    a: Annotated[int, Param.store(
        parsers.int_parser.validated(int_is_not_negative, "The value cannot be negative")
    )]
    
    b: Annotated[int, Param.store(
        parsers.int_parser.validated(int_is_not_negative, "The value cannot be negative")
        )]

    def validate_a_is_greater_than_b(self) -> Optional[Err]:
        if not self.a > self.b:
            return Err.make(f"The value a={self.a} needs to be greater than the value b={self.b}")
        else:
            return None
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 2>[0;34m()[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdataclasses[39;00m [38;5;28;01mimport[39;00m dataclass
[0;32m----> 2[0m [38;5;28;01mfrom[39;00m [38;5;21;01mconfigpile[39;00m [38;5;28;01mimport[39;00m [38;5;241m*[39m
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtyping_extensions[39;00m [38;5;28;01mimport[39;00m Annotated
[1;32m      4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mtyping[39;00m [38;5;28;01mimport[39;00m Optional

[0;31mAttributeError[0m: module 'configpile' has no attribute 'fun'
AttributeError: module 'configpile' has no attribute 'fun'

